name : Crawl New hole by pages (part I)
on :
  workflow_dispatch:
  schedule:
    - cron : '0 16,4 * * *'
    
jobs:
  crawling:
    runs-on: ubuntu-latest
    steps:
    - name: check out repository
      uses: actions/checkout@v1
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: requirements
      run: |
        pip install requests
        pip install argparse
        pip install tqdm
        pip install func_timeout

    - name: crawl_json
      run: |
        python main.py --update 2

    - name: Get Time
      id : time
      uses: josStorer/get-current-time@v2.0.0
      with:
        utcOffset: "+08:00"

    - name: git_add
      run: |
        git config --global user.email 1978633500@qq.com
        git config --global user.name kaleidoscope
        git add .
        git commit -m "Crawl_${{steps.time.outputs.readableTime}}"

    - name: git_push
      uses: ad-m/github-push-action@master
      with: 
        github_token: ${{secrets.ACCESS_TOKEN}}
 
