name : Reloading images and movies
on :
  workflow_dispatch:
    
jobs:
  image_confirm:
    runs-on: ubuntu-latest
    steps:
    - name: check out repository
      uses: actions/checkout@v1
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: requirements
      run: |
        pip install requests
        pip install tqdm
        pip install argparse
        pip install func_timeout

    - name: img_confirm
      run: |
          python img_confirm.py
          
    - name: img_reload
      run: |
          python img_reload.py --e True

    - name: Get Time
      id : time
      uses: josStorer/get-current-time@v2.0.0
      with:
        utcOffset: "+08:00"

    - name: git_add
      run: |
        git config --global user.email 1978633500@qq.com
        git config --global user.name kaleidoscope
        git add .
        git commit -m "Reload_${{steps.time.outputs.readableTime}}"
     
    - name: git_push
      uses: ad-m/github-push-action@master
      with: 
        github_token: ${{secrets.ACCESS_TOKEN}}
 
